<?php

namespace app\modules\api\controllers;

use common\models\Organization;
use common\models\Region;

class RegionController extends ApiActiveController
{
    public $modelClass = 'common\models\Region';

    /*public function actions()
    {
        $action = parent::actions(); // TODO: Change the autogenerated stub
        unset($action['view']);
        return $action;
    }

    public function actionView($id)
    {
        $region = Region::findOne($id);
        $organizations = Organization::find()->where(['region_id' => $id])->all();
        return array_merge(array($region->id, $region->name_tj, $region->name_en, $region->name_ru), $organizations);
    }*/
}